// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBChusKmxbbzwbJGN5QutmF6C2rOuuvvT0',
    appId: '1:651724281846:web:8479ada019cac12f5f19d7',
    messagingSenderId: '651724281846',
    projectId: 'laundry-213c2',
    authDomain: 'laundry-213c2.firebaseapp.com',
    storageBucket: 'laundry-213c2.firebasestorage.app',
    measurementId: 'G-57ZQWP0FWE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLq8_Ek93gzAM6hF6skQUwFu8QoeClBEo',
    appId: '1:651724281846:android:fd497eee04b122e45f19d7',
    messagingSenderId: '651724281846',
    projectId: 'laundry-213c2',
    storageBucket: 'laundry-213c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7D8Q-dAgawqrppZtlQgCzOa8OSsrm2Xk',
    appId: '1:651724281846:ios:035cf05b1ed23caa5f19d7',
    messagingSenderId: '651724281846',
    projectId: 'laundry-213c2',
    storageBucket: 'laundry-213c2.firebasestorage.app',
    iosBundleId: 'com.laundryapp.laundry',
  );

}